name: release
on:
  push:
    branch: default

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: lsp
      - name: Package
        shell: bash
        run: |
          make -C lsp deps
          zip -r lsp.zip lsp -x "lsp/.git*"
      - name: Tag
        run: |
          cd lsp
          git tag latest
          git push -f origin latest
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: latest
          tag: latest
          allowUpdates: true
          body: Latest automated build (ignore github-actions' release date)
          artifacts: lsp.zip
          token: ${{ secrets.GITHUB_TOKEN }}
  cleanup:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Remove older build artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 minute'
