name: release
on:
  push:
    branch: default

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package
        shell: bash
        run: |
          mkdir -p build/_deps && mv textadept-build/* build/_deps && rm -r textadept-build
          cmake -S . -B build -D CMAKE_INSTALL_PREFIX=build/install
          cmake --build build --config Release -j
          cmake --install build --config Release
      - name: Tag
        run: |
          git tag latest
          git push -f origin latest
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: latest
          tag: latest
          allowUpdates: true
          body: Latest automated build (ignore github-actions' release date)
          artifacts: lsp.zip
          token: ${{ secrets.GITHUB_TOKEN }}
  cleanup:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Remove older build artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 minute'
