name: release
on:
  push:
    branch: default

jobs:
  build-winapi:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout textadept-build dependencies
        uses: actions/checkout@v3
        with:
          repository: orbitalquark/textadept-build
          path: textadept-build
      - name: Build
        shell: bash
        run: |
          mkdir -p build/_deps && mv textadept-build/* build/_deps && rm -r textadept-build
          cmake -S . -B build -D CMAKE_INSTALL_PREFIX=build/install
          cmake --build build --config Release --target winapi -j
          cmake --install build --config Release
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            *.dll
  release:
    runs-on: ubuntu-latest
    needs: build-winapi
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - name: Package
        shell: bash
        run: |
          mkdir -p build/_deps && mv textadept-build/* build/_deps && rm -r textadept-build
          cmake -S . -B build -D CMAKE_INSTALL_PREFIX=build/install
          cmake --build build --config Release -j
          cmake --install build --config Release
          git archive HEAD --prefix lsp/ | tar -xf -
          mv dkjson.lua ldoc ldoc.lua logging pl *.dll lsp
          zip -r lsp.zip lsp
      - name: Tag
        run: |
          git tag latest
          git push -f origin latest
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: latest
          tag: latest
          allowUpdates: true
          body: Latest automated build (ignore github-actions' release date)
          artifacts: lsp.zip
          token: ${{ secrets.GITHUB_TOKEN }}
  cleanup:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Remove older build artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 minute'
